---
# PHP
app_server_name: api-backend.avalanche
app_server_ip: 127.0.0.1
haproxy_ip: 172.20.0.24
php_app_php_version: 7.1
php_app_php_extra_packages:
  - php7.1-mcrypt

# User for php app. Needed also by other modules
php_app_user: forge


# Nginx
nginx_sites:
  example.api.site:
    - listen 80
    - server_name {{ app_server_name }}
    - "root /home/{{ php_app_user }}/{{ app_server_name }}/current/public"
    - error_page 404 /index.php
    - access_log /var/log/nginx/{{ app_server_name }}.access.log
    - error_log /var/log/nginx/{{ app_server_name }}.error.log error
    - include snippets/avalanche.conf